/*
 *     Copyright 2026 The Dragonfly Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package util

import "path"

// FileSize is the size of a file in bytes.
type FileSize = uint64

const (
	// FileSize1MiB represents the size of 1MiB.
	FileSize1MiB FileSize = 1024 * 1024

	// FileSize10MiB represents the size of 10MiB.
	FileSize10MiB FileSize = 10 * FileSize1MiB

	// FileSize1GiB represents the size of 1GiB.
	FileSize1GiB FileSize = 1024 * FileSize1MiB
)

// File represents a file on the file server.
type File struct {
	// name is the file name, the sha256 of the file content.
	name string

	// downloadURL is the download URL of the file from the file server.
	downloadURL string
}

// GetSha256 returns the sha256 of the file content.
func (f *File) GetSha256() string {
	return f.name
}

// GetDownloadURL returns the download URL of the file from the file server.
func (f *File) GetDownloadURL() string {
	return f.downloadURL
}

// GetTaskID returns the task id of the file, as generated by a request with
// the default options of the SDKs.
func (f *File) GetTaskID() string {
	return TaskID(f.downloadURL)
}

// GetOutputPath returns the output path of the file in the runner pod.
func (f *File) GetOutputPath() string {
	return path.Join("/tmp", f.name)
}
