/*
 *     Copyright 2026 The Dragonfly Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package util

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

const (
	// dufsFileServerEndpoint is the endpoint of the dufs file server in the
	// cluster, the seed peers download the files from it.
	dufsFileServerEndpoint = "http://dufs.dragonfly-e2e.svc"

	// dufsFileServerLocalDir is the local directory of the dufs file server,
	// shared with the file server pod through the kind nodes.
	dufsFileServerLocalDir = ArtifactDir + "/dufs"
)

var (
	// globalFileServer is the global file server instance.
	globalFileServer FileServer

	// once is the sync.Once instance for globalFileServer.
	once sync.Once
)

// NewFileServer creates a new file server which using the singleton pattern.
func NewFileServer() (FileServer, error) {
	var err error
	once.Do(func() {
		globalFileServer, err = newDufsFileServer()
	})

	return globalFileServer, err
}

// GetFileServer returns the global file server instance.
func GetFileServer() FileServer {
	return globalFileServer
}

// FileServer is the interface of file server for testing.
type FileServer interface {
	// GenerateFile generates a file by random data with the specified size.
	GenerateFile(size FileSize) (*File, error)

	// DeleteFile deletes the file.
	DeleteFile(file *File) error

	// RequestCount returns the number of downloads of the file the file server
	// served, from its access log.
	RequestCount(file *File) (int, error)

	// Purge deletes all files generated by the file server, it should be called
	// after all tests.
	Purge() error
}

// dufsFileServer represents a file server implemented by project
// dufs(https://github.com/sigoden/dufs).
type dufsFileServer struct {
	// endpoint is the endpoint of the file server in the cluster.
	endpoint string

	// localDir is the local directory of the file server.
	localDir string
}

// newDufsFileServer creates a new dufs file server.
func newDufsFileServer() (*dufsFileServer, error) {
	if err := os.MkdirAll(dufsFileServerLocalDir, 0777); err != nil {
		return nil, err
	}

	return &dufsFileServer{
		endpoint: dufsFileServerEndpoint,
		localDir: dufsFileServerLocalDir,
	}, nil
}

// GenerateFile generates a file by the size in the local directory of the file
// server and returns the File instance.
func (fs *dufsFileServer) GenerateFile(size FileSize) (*File, error) {
	data := make([]byte, size)
	if _, err := rand.Read(data); err != nil {
		return nil, err
	}

	hash := sha256.Sum256(data)
	name := hex.EncodeToString(hash[:])
	if err := os.WriteFile(filepath.Join(fs.localDir, name), data, 0666); err != nil {
		return nil, err
	}

	return &File{
		name:        name,
		downloadURL: fmt.Sprintf("%s/%s", fs.endpoint, name),
	}, nil
}

// DeleteFile deletes the file from the local directory of the file server.
func (fs *dufsFileServer) DeleteFile(file *File) error {
	return os.RemoveAll(filepath.Join(fs.localDir, file.name))
}

// RequestCount counts the downloads of the file in the access log of the file
// server, which logs every request as `<remote addr> "<method> <path>" <status>`,
// e.g. `10.244.1.3 "GET /<name>" 206`. Both the HEAD and the GET requests of
// the seed peers are counted.
func (fs *dufsFileServer) RequestCount(file *File) (int, error) {
	podNames, err := GetPodNames(E2ENamespace, FileServerName)
	if err != nil {
		return 0, err
	}

	count := 0
	for _, podName := range podNames {
		out, err := KubeCtlCommand("-n", E2ENamespace, "logs", podName).CombinedOutput()
		if err != nil {
			return 0, fmt.Errorf("get logs of %s/%s: %w, output: %s", E2ENamespace, podName, err, out)
		}

		for _, method := range []string{http.MethodGet, http.MethodHead} {
			count += strings.Count(string(out), fmt.Sprintf(`"%s /%s"`, method, file.name))
		}
	}

	return count, nil
}

// Purge cleans up all files generated by the file server, keeping the local
// directory itself since the file server pod bind mounts it.
func (fs *dufsFileServer) Purge() error {
	entries, err := os.ReadDir(fs.localDir)
	if err != nil {
		return err
	}

	for _, entry := range entries {
		if err := os.RemoveAll(filepath.Join(fs.localDir, entry.Name())); err != nil {
			return err
		}
	}

	return nil
}
