/*
 *     Copyright 2026 The Dragonfly Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package util

import (
	"fmt"
	"path"
	"strings"
)

// BusyboxImage is the image the tests preheat, with the digests of its
// manifest, config and layer.
var BusyboxImage = &Image{
	registry:       "ghcr.io",
	repository:     "dragonflyoss/busybox",
	tag:            "1.35.0",
	manifestDigest: "sha256:e39d9c8ac4963d0b00a5af08678757b44c35ea8eb6be0cdfbeb1282e7f7e6003",
	blobDigests: []string{
		"sha256:a711f05d33845e2e9deffcfcc5adf082d7c6e97e3e3a881d193d9aae38f092a8",
		"sha256:f643e116a03d9604c344edb345d7592c48cc00f2a4848aaf773411f4fb30d2f5",
	},
}

// Image represents an OCI image on a registry.
type Image struct {
	// registry is the registry host of the image.
	registry string

	// repository is the repository of the image.
	repository string

	// tag is the tag of the image.
	tag string

	// manifestDigest is the digest of the image manifest, the preheat downloads
	// the manifest referenced by its digest.
	manifestDigest string

	// blobDigests are the digests of the config and the layers of the image.
	blobDigests []string
}

// GetReference returns the image reference, e.g. ghcr.io/dragonflyoss/busybox:1.35.0.
func (i *Image) GetReference() string {
	return fmt.Sprintf("%s/%s:%s", i.registry, i.repository, i.tag)
}

// GetRegistry returns the registry host of the image.
func (i *Image) GetRegistry() string {
	return i.registry
}

// GetRepository returns the repository of the image.
func (i *Image) GetRepository() string {
	return i.repository
}

// GetBlobs returns the manifest, the config and the layers of the image, as the
// preheat downloads them.
func (i *Image) GetBlobs() []*Blob {
	blobs := []*Blob{{
		url:    fmt.Sprintf("https://%s/v2/%s/manifests/%s", i.registry, i.repository, i.manifestDigest),
		digest: i.manifestDigest,
	}}

	for _, digest := range i.blobDigests {
		blobs = append(blobs, &Blob{
			url:    fmt.Sprintf("https://%s/v2/%s/blobs/%s", i.registry, i.repository, digest),
			digest: digest,
		})
	}

	return blobs
}

// Blob represents a manifest, a config or a layer of an image, addressed by its
// digest on the registry.
type Blob struct {
	// url is the url of the blob on the registry.
	url string

	// digest is the digest of the blob, e.g. sha256:<encoded>.
	digest string
}

// GetURL returns the url of the blob on the registry.
func (b *Blob) GetURL() string {
	return b.url
}

// GetSha256 returns the sha256 of the blob content, the encoded digest.
func (b *Blob) GetSha256() string {
	return strings.TrimPrefix(b.digest, "sha256:")
}

// GetTaskID returns the task id of the blob, as generated by a request with
// the default options of the SDKs.
func (b *Blob) GetTaskID() string {
	return TaskID(b.url)
}

// GetOutputPath returns the output path of the blob in the runner pod.
func (b *Blob) GetOutputPath() string {
	return path.Join("/tmp", b.GetSha256())
}
