/*
 *     Copyright 2026 The Dragonfly Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package util

import (
	"errors"
	"fmt"
	"strings"

	"d7y.io/dragonfly/v2/pkg/idgen"
)

const (
	// seedClientContentDir is the content directory of the seed clients, the
	// storage dir of the dragonfly chart plus the content dir of dfdaemon.
	seedClientContentDir = "/var/lib/dragonfly/content"
)

// TaskID returns the task id of the url, as generated by a request with the
// default options of the SDKs: the default filtered query params, no tag, no
// application and the blob digest based task id enabled.
func TaskID(url string) string {
	id, err := idgen.TaskIDV2(url, nil, "", "", idgen.DefaultFilteredQueryParams, "", true)
	if err != nil {
		panic(fmt.Sprintf("generate task id of %s: %v", url, err))
	}

	return id
}

// CheckFilesExist reports whether any of the pods holds the task content.
func CheckFilesExist(pods []*PodExec, taskID string) bool {
	for _, pod := range pods {
		contentPath := taskContentPath(taskID)
		if _, err := pod.Command("ls", contentPath).CombinedOutput(); err != nil {
			fmt.Printf("path %s does not exist in %s: %s\n", contentPath, pod.Name(), err.Error())
			continue
		}

		return true
	}

	return false
}

// CalculateSha256ByTaskID calculates the sha256 of the task content held by
// the first of the pods that holds it.
func CalculateSha256ByTaskID(pods []*PodExec, taskID string) (string, error) {
	return calculateSha256(pods, taskContentPath(taskID))
}

// CalculateSha256ByOutput calculates the sha256 of the output file held by the
// first of the pods that holds it.
func CalculateSha256ByOutput(pods []*PodExec, output string) (string, error) {
	return calculateSha256(pods, output)
}

// calculateSha256 calculates the sha256 of the file held by the first of the
// pods that holds it.
func calculateSha256(pods []*PodExec, path string) (string, error) {
	for _, pod := range pods {
		if _, err := pod.Command("ls", path).CombinedOutput(); err != nil {
			fmt.Printf("path %s does not exist in %s: %s\n", path, pod.Name(), err.Error())
			continue
		}

		out, err := pod.Command("sha256sum", path).CombinedOutput()
		if err != nil {
			return "", fmt.Errorf("calculate sha256sum of %s in %s failed: %s", path, pod.Name(), err.Error())
		}

		fmt.Println("sha256sum: " + string(out))
		return strings.Fields(string(out))[0], nil
	}

	return "", errors.New("can not found sha256sum")
}

// taskContentPath returns the path of the task content in a seed client.
func taskContentPath(taskID string) string {
	return fmt.Sprintf("%s/tasks/%s/%s", seedClientContentDir, taskID[:3], taskID)
}
